---
    - name: Disable mouse acceleration
      shell: defaults write .GlobalPreferences com.apple.mouse.scaling -1

    - name: "Key Repeat: Fast (all the way to the right)"
      shell: defaults write -g InitialKeyRepeat -int 15

    - name: "Delay Until Repeat: Short (all the way to the right)"
      shell: defaults write -g KeyRepeat -int 2

    - name: "Untick 'Correct spelling automatically'"
      shell: defaults write -g NSAutomaticSpellingCorrectionEnabled -bool false

    - name: "Untick 'Add full stop with double-space'"
      shell: defaults write -g NSAutomaticPeriodSubstitutionEnabled -bool false

    - name: Disable mouse acceleration
      shell: defaults write .GlobalPreferences com.apple.mouse.scaling -1

    - name: "Set Keybord Shortcut 'Move focus to next window' to Command+$"
      shell: |
        /usr/libexec/PlistBuddy -c 'Delete :AppleSymbolicHotKeys:27' ~/Library/Preferences/com.apple.symbolichotkeys.plist
        /usr/libexec/PlistBuddy -c 'Add :AppleSymbolicHotKeys:27:enabled bool 1' ~/Library/Preferences/com.apple.symbolichotkeys.plist
        /usr/libexec/PlistBuddy -c 'Add :AppleSymbolicHotKeys:27:value:type string standard' ~/Library/Preferences/com.apple.symbolichotkeys.plist
        /usr/libexec/PlistBuddy -c 'Add :AppleSymbolicHotKeys:27:value:parameters array' ~/Library/Preferences/com.apple.symbolichotkeys.plist
        /usr/libexec/PlistBuddy -c 'Add :AppleSymbolicHotKeys:27:value:parameters:0 integer 36' ~/Library/Preferences/com.apple.symbolichotkeys.plist
        /usr/libexec/PlistBuddy -c 'Add :AppleSymbolicHotKeys:27:value:parameters:1 integer 10' ~/Library/Preferences/com.apple.symbolichotkeys.plist
        /usr/libexec/PlistBuddy -c 'Add :AppleSymbolicHotKeys:27:value:parameters:2 integer 1048576' ~/Library/Preferences/com.apple.symbolichotkeys.plist
       
    - name: Download Powerline fonts
      git:
        repo: https://github.com/powerline/fonts.git
        dest: $HOME/fonts
        depth: 1

    - name: Install powerline fonts
      shell: cp -r $HOME/fonts/*/*.ttf /Library/Fonts/.
      